INSERT INTO expense_types (name, created_at, updated_at) VALUES
('Rent', now(), now()),
('Water bill', now(), now()),
('Electricity bill', now(), now()),
('Groceries', now(), now()),
('Restaurants / Delivery', now(), now()),
('Transportation', now(), now()),
('Health', now(), now()),
('Education', now(), now()),
('Entertainment', now(), now()),
('Clothing', now(), now()),
('Beauty', now(), now()),
('Gifts', now(), now()),
('Others', now(), now()),
('Vehicle maintenance', now(), now()),
('Home maintenance', now(), now()),
('Insurance', now(), now()),
('Taxes', now(), now()),
('Investments', now(), now()),
('Savings', now(), now()),
('Debts', now(), now()),
('Loans', now(), now()),
('Credit card', now(), now()),
('Salary', now(), now()),
('Freelance', now(), now()),
('Investments', now(), now()),
('Savings', now(), now()),
('Others', now(), now());
